dist: xenial
language: ruby
rvm:
- 2.4.3
env:
  global:
    - FRAMEWORK_BRANCH=main
jobs:
  include:
    - stage: deploy
      if: branch = main OR repo =~ /-internal/
      before_install:
      - echo -e "machine github.com\n login $GH_TOKEN" > ~/.netrc && chmod 600 ~/.netrc
      - git submodule add -b $FRAMEWORK_BRANCH https://github.com/NetAppDocs/jekyll dependencies/jekyll
      - gem update --system && gem install bundler && gem update bundler
      - if [[ -z "$DEPLOY_BRANCH" ]]; then export DEPLOY_BRANCH=gh-pages; fi

- cp -rl dependencies/jekyll/search.html ./high-availability/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ high-availability\/search\.html/g' ./high-availability/search.html
- cp -rl dependencies/jekyll/search.html ./networking/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ networking\/search\.html/g' ./networking/search.html
- cp -rl dependencies/jekyll/search.html ./revert/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ revert\/search\.html/g' ./revert/search.html
- cp -rl dependencies/jekyll/search.html ./smbc/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ smbc\/search\.html/g' ./smbc/search.html
- cp -rl dependencies/jekyll/search.html ./software_setup/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ software_setup\/search\.html/g' ./software_setup/search.html
- cp -rl dependencies/jekyll/search.html ./upgrade/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ upgrade\/search\.html/g' ./upgrade/search.html
- mv dependencies/jekyll/prod-build.sh ./ && ./prod-build.sh
- sudo apt-get -y install graphicsmagick graphicsmagick-libmagick-dev-compat libmagickwand-dev
install: bundle install --quiet --jobs=3 --retry=3
 script:
      - if [[ ! -z "$FEATURE_FLAG" ]]; then bundle exec rake buildAll; fi
      - mkdir -p /tmp/output && bundle exec jekyll build --trace --destination /tmp/output
      - touch /tmp/output/.nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        keep_history: false
        local_dir: /tmp/output
        target_branch: $DEPLOY_BRANCH
        verbose: true
        on:
          all_branches: true
    - state: i18n
      if: branch = main OR repo =~ /-internal/
      before_install:
      - echo -e "machine github.com\n login $GH_TOKEN" >> ~/.netrc && chmod 600 ~/.netrc
      - git submodule add https://github.com/NetAppDocs/jekyll-harmony dependencies/jekyll-harmony
      - gem update --system && gem install bundler && gem update bundler
      install:
      - cd dependencies/jekyll-harmony
      - bundle install --jobs=3 --retry=3
      - bundle exec rake install
      - cd -
      script:
      - if [[ ! -z "$HARMONY_FLAG" ]]; then i18n-translate; fi
