settings:
  name: "ONTAP 9"
  pdf_enabled: true

sidebar:
  entries:
    - title: ONTAP docs
      url: /index.html
    - title: Release Notes
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
    - section: introduction-concepts
    - section: setup-upgrade
    - section: cluster-admin
    - section: volume-admin
    - section: network-management
    - section: nas-management
    - section: san-management
    - section: object-storage-management
    - section: security-encryption
    - section: data-protection-disaster-recovery
    - section: event-performance-monitoring
    - title: Notices
      url: /reference_legal_notices.html
